@baseUrl = http://127.0.0.1:3002

### 1. Membuat penalty baru
POST {{baseUrl}}/penalties
Content-Type: application/json

{
  "installmentId": 5,
  "penaltyAmount": 29000,
  "penaltyReason": "Denda harian"
}

### 2. Mendapatkan semua penalty
GET {{baseUrl}}/penalties
Accept: application/json

### 3. Mengupdate penalty
PATCH {{baseUrl}}/penalties/1
Content-Type: application/json

{
  "installmentId": 5,
  "penaltyAmount": 25000,
  "penaltyReason": "Denda keterlambatan kedua"
}

### 4. Mendapatkan satu penalty berdasarkan ID
GET {{baseUrl}}/penalties/1
Accept: application/json

### 5. Menghapus penalty berdasarkan ID
DELETE {{baseUrl}}/penalties/1
Accept: application/json
