@baseUrl = http://127.0.0.1:3002

### 1. Membuat penalty baru
POST {{baseUrl}}/penalties
Content-Type: application/json

{
  "installmentId": 3,
  "penaltyAmount": 20000,
  "penaltyReason": "Denda keterlambatan"
}

### 2. Mendapatkan semua penalty
GET {{baseUrl}}/penalties
Accept: application/json

### 3. Mengupdate penalty
PUT {{baseUrl}}/penalties/2
Content-Type: application/json

{
  "installmentId": 2,
  "penaltyAmount": 20000,
  "penaltyReason": "Denda keterlambatan"
}

### 3. Mendapatkan satu penalty berdasarkan ID
GET {{baseUrl}}/penalties/1
Accept: application/json

### 4. Menghapus penalty berdasarkan ID
DELETE {{baseUrl}}/penalties/1
Accept: application/json
